import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi Norvillie !

        </h1>

        <p className={styles.description}>
          Now are going to start new project: 
          e-app
          
        </p>
        <p className={styles.description}>
         
           <code className={styles.code}>(if you have a better idea of the name just tell it)</code>
        </p>


        
      </main>

      <footer className={styles.footer}>
        
        2022
      </footer>
    </div>
  )
}
